version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=lyricThing
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DATABASE=lyricthing
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
    driver: local
